common/urls.py
import os

from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.generic import RedirectView
from django.views.static import serve

from candidats import views as candidats_views
from stages import views

urlpatterns = [
    path('', RedirectView.as_view(url='/admin/', permanent=True), name='home'),

    path('admin/', admin.site.urls),

    path('import_students/', views.StudentImportView.as_view(), name='import-students'),
    path('import_students_ester/', views.imports.StudentEsterImportView.as_view(), name='import-students-ester'),
    path('import_hp/', views.HPImportView.as_view(), name='import-hp'),
    path('import_hp_contacts/', views.HPContactsImportView.as_view(), name='import-hp-contacts'),

    path('attribution/', views.AttributionView.as_view(), name='attribution'),
    re_path(r'^stages/export/(?P<scope>all)?/?$', views.export.stages_export, name='stages_export'),

    path('institutions/', views.CorporationListView.as_view(), name='corporations'),
    path('institutions/<int:pk>/', views.CorporationView.as_view(), name='corporation'),
    path('institutions/merge/', views.CorporationMergeView.as_view(), name='corporations-merge'),
    path('institutions/export/', views.export.institutions_export, name='corporations-export'),

    path('classes/', views.KlassListView.as_view(), name='classes'),
    path('classes/<int:pk>/', views.KlassView.as_view(), name='class'),
    path('classes/<int:pk>/import_reports/', views.ImportReportsView.as_view(),
        name='import-reports'),
    path('classes/print_klass_list/', views.PrintKlassList.as_view(), name='print-klass-list'),
    path('student/<int:pk>/comment/', views.StudentCommentView.as_view(), name='student-comment'),

    path('candidate/<int:pk>/send_convocation/', candidats_views.ConvocationView.as_view(),
        name='candidate-convocation'),
    path('candidate/<int:pk>/send_confirmation/', candidats_views.ConfirmationView.as_view(),
        name='candidate-confirmation'),
    path('candidate/<int:pk>/send_validation/', candidats_views.ValidationView.as_view(),
        name='candidate-validation'),
    path('candidate/<int:pk>/summary/', candidats_views.inscription_summary, name='candidate-summary'),

    path('student/<int:pk>/examination/mentor/', views.PrintCompensationForm.as_view(), {'typ': 'mentor'},
        name='print-mentor-compens-form'),
    path('student/<int:pk>/examination/supervisor/', views.PrintCompensationForm.as_view(), {'typ': 'supervisor'},
        name='print-supervisor-compens-form'),
    path('exam/<int:pk>/indemn/<slug:typ>/', views.PrintCompensationForm.as_view(),
        name='print-compens-form'),
    path('expert/<int:pk>/info/', views.PrintExpertInfoForm.as_view(), name='print-supervisor-info'),

    # Qualification EDE
    path('student_ede/<int:pk>/send_convocation/', views.StudentConvocationExaminationView.as_view(),
        name='student-ede-convocation'),
    path('student_ede/<int:pk>/examination/expert/', views.PrintExpertEDECompensationForm.as_view(),
        name='print-expert-letter-ede'),

    # Qualification EDS
    path('student_eds/<int:pk>/send_convocation/', views.StudentConvocationEDSView.as_view(),
        name='student-eds-convocation'),
    path('student_eds/<int:pk>/examination/expert/', views.PrintExpertEDSCompensationForm.as_view(),
        name='print-expert-letter-eds'),

    path('student/export_qualif/', views.export.export_qualification, name='export-qualif'),

    path('imputations/export/', views.export.imputations_export, name='imputations_export'),
    path('print/update_form/', views.PrintUpdateForm.as_view(), name='print_update_form'),
    path('print/charge_sheet/', views.PrintChargeSheet.as_view(), name='print-charge-sheet'),
    path('general_export/', views.export.general_export, name='general-export'),
    path('ortra_export/', views.export.ortra_export, name='ortra-export'),

    # AJAX/JSON urls
    path('section/<int:pk>/periods/', views.section_periods, name='section_periods'),
    path('section/<int:pk>/classes/', views.section_classes, name='section_classes'),
    path('period/<int:pk>/students/', views.period_students, name='period_students'),
    path('period/<int:pk>/corporations/', views.period_availabilities, name='period_availabilities'),
    # Training params in POST:
    path('training/new/', views.new_training, name="new_training"),
    path('training/del/', views.del_training, name="del_training"),
    path('training/by_period/<int:pk>/', views.TrainingsByPeriodView.as_view()),

    path('student/<int:pk>/summary/', views.StudentSummaryView.as_view()),
    path('student/<int:pk>/send_reports/sem/<int:semestre>/', views.SendStudentReportsView.as_view(),
        name='send-student-reports'),
    path('availability/<int:pk>/summary/', views.AvailabilitySummaryView.as_view()),
    path('corporation/<int:pk>/contacts/', views.CorpContactJSONView.as_view()),

    path('summernote/', include('django_summernote.urls')),
    # Serve bulletins by Django to allow LoginRequiredMiddleware to apply
    path('media/bulletins/<path:path>', serve,
        {'document_root': os.path.join(settings.MEDIA_ROOT, 'bulletins'), 'show_indexes': False}
    ),
]

stages/models.py
import json
from collections import OrderedDict
from contextlib import suppress
from datetime import date, timedelta

from django.conf import settings
from django.db import models
from django.db.models import Case, Count, When

from . import utils

CIVILITY_CHOICES = (
    ('Madame', 'Madame'),
    ('Monsieur', 'Monsieur'),
)


class Section(models.Model):
    """ Filières """
    name = models.CharField("Nom", max_length=20)
    has_stages = models.BooleanField("Planifie la PP sur ce site", default=False)

    class Meta:
        verbose_name = "Filière"

    def __str__(self):
        return self.name

    @property
    def is_fe(self):
        """fe=formation en entreprise"""
        return self.name in {'ASA', 'ASE', 'ASSC'}

    @property
    def is_EPC(self):
        return self.name in {'ASA', 'ASE', 'ASSC', 'EDE', 'EDS'}

    @property
    def is_ESTER(self):
        return self.name in {'MP_ASE', 'MP_ASSC'}


class Level(models.Model):
    name = models.CharField(max_length=10, verbose_name='Nom')

    class Meta:
        verbose_name = "Niveau"
        verbose_name_plural = "Niveaux"

    def __str__(self):
        return self.name

    def delta(self, diff):
        if diff == 0:
            return self
        try:
            return Level.objects.get(name=str(int(self.name)+diff))
        except Level.DoesNotExist:
            return None


class ActiveKlassManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().annotate(
            num_students=Count(Case(When(student__archived=False, then=1)))
        ).filter(num_students__gt=0)


class Klass(models.Model):
    name = models.CharField(max_length=10, verbose_name='Nom', unique=True)
    section = models.ForeignKey(Section, verbose_name='Filière', on_delete=models.PROTECT)
    level = models.ForeignKey(Level, verbose_name='Niveau', on_delete=models.PROTECT)
    teacher = models.ForeignKey('Teacher', blank=True, null=True,
        on_delete=models.SET_NULL, verbose_name='Maître de classe')
    teacher_ecg = models.ForeignKey('Teacher', blank=True, null=True,
        on_delete=models.SET_NULL, verbose_name='Maître ECG', related_name='+')
    teacher_eps = models.ForeignKey('Teacher', blank=True, null=True,
        on_delete=models.SET_NULL, verbose_name='Maître EPS', related_name='+')

    objects = models.Manager()
    active = ActiveKlassManager()

    class Meta:
        verbose_name = "Classe"

    def __str__(self):
        return self.name

    def is_Ede_pe(self):
        return 'EDE' in self.name and 'pe' in self.name

    def is_Ede_ps(self):
        return 'EDE' in self.name and 'ps' in self.name


class Teacher(models.Model):
    civility = models.CharField(max_length=10, choices=CIVILITY_CHOICES, verbose_name='Civilité')
    first_name = models.CharField(max_length=40, verbose_name='Prénom')
    last_name = models.CharField(max_length=40, verbose_name='Nom')
    abrev = models.CharField(max_length=10, verbose_name='Sigle')
    birth_date = models.DateField(verbose_name='Date de naissance', blank=True, null=True)
    email = models.EmailField(verbose_name='Courriel', blank=True)
    contract = models.CharField(max_length=20, verbose_name='Contrat')
    rate = models.DecimalField(default=0.0, max_digits=4, decimal_places=1, verbose_name="Taux d'activité")
    ext_id = models.IntegerField(blank=True, null=True)
    previous_report = models.IntegerField(default=0, verbose_name='Report précédent')
    next_report = models.IntegerField(default=0, verbose_name='Report suivant')
    can_examinate = models.BooleanField("Peut corriger examens candidats", default=False)
    archived = models.BooleanField(default=False)
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True,
        verbose_name='Compte utilisateur'
    )

    class Meta:
        verbose_name='Enseignant'
        ordering = ('last_name', 'first_name')

    def __str__(self):
        return '{0} {1}'.format(self.last_name, self.first_name)

    @property
    def full_name(self):
        return '{0} {1}'.format(self.first_name, self.last_name)

    @property
    def civility_full_name(self):
        return '{0} {1} {2}'.format(self.civility, self.first_name, self.last_name)

    @property
    def role(self):
        return {'Monsieur': 'enseignant-formateur', 'Madame': 'enseignante-formatrice'}.get(self.civility, '')

    def calc_activity(self):
        """
        Return a dictionary of calculations relative to teacher courses.
        Store plus/minus periods to self.next_report.
        """
        mandats = self.course_set.filter(subject__startswith='#')
        ens = self.course_set.exclude(subject__startswith='#')
        tot_mandats = mandats.aggregate(models.Sum('period'))['period__sum'] or 0
        tot_ens = ens.aggregate(models.Sum('period'))['period__sum'] or 0
        # formation periods calculated at pro-rata of total charge
        tot_formation = int(round(
            (tot_mandats + tot_ens) / settings.MAX_ENS_PERIODS * settings.MAX_ENS_FORMATION
        ))
        tot_trav = self.previous_report + tot_mandats + tot_ens + tot_formation
        tot_paye = tot_trav
        max_periods = settings.MAX_ENS_PERIODS + settings.MAX_ENS_FORMATION
        # Special situations triggering reporting (positive or negative) hours for next year:
        #  - full-time teacher with a total charge under 100%
        #  - teachers with a total charge over 100%
        self.next_report = 0
        if (self.rate == 100 and tot_paye < max_periods) or (tot_paye > max_periods):
            tot_paye = max_periods
            self.next_report = tot_trav - tot_paye
        self.save()

        return {
            'mandats': mandats,
            'tot_mandats': tot_mandats,
            'tot_ens': tot_ens,
            'tot_formation': tot_formation,
            'tot_trav': tot_trav,
            'tot_paye': tot_paye,
            'report': self.next_report,
        }

    def calc_imputations(self, ratios):
        """
        Return a tuple for accountings charges
        """
        activities = self.calc_activity()
        imputations = OrderedDict(
            [('ASAFE', 0), ('ASSCFE', 0), ('ASEFE', 0), ('MPTS', 0), ('MPS', 0), ('EDEpe', 0), ('EDEps', 0),
             ('EDS', 0), ('CAS_FPP', 0)]
        )
        courses = self.course_set.all()

        for key in imputations:
            imputations[key] = courses.filter(imputation__contains=key).aggregate(models.Sum('period'))['period__sum'] or 0

        # Spliting imputations for EDE, ASE and ASSC
        ede = courses.filter(imputation='EDE').aggregate(models.Sum('period'))['period__sum'] or 0
        if ede > 0:
            pe = int(round(ede * ratios['edepe'], 0))
            imputations['EDEpe'] += pe
            imputations['EDEps'] += ede - pe

        ase = courses.filter(imputation='ASE').aggregate(models.Sum('period'))['period__sum'] or 0
        if ase > 0:
            asefe = int(round(ase * ratios['asefe'], 0))
            imputations['ASEFE'] += asefe
            imputations['MPTS'] += ase - asefe

        assc = courses.filter(imputation='ASSC').aggregate(models.Sum('period'))['period__sum'] or 0
        if assc > 0:
            asscfe = int(round(assc * ratios['asscfe'], 0))
            imputations['ASSCFE'] += asscfe
            imputations['MPS'] += assc - asscfe

        # Split formation periods in proportions
        tot = sum(imputations.values())
        if tot > 0:
            for key in imputations:
                imputations[key] += round(imputations[key] / tot * activities['tot_formation'],0)

        return (activities, imputations)

    def total_logbook(self):
        return LogBook.objects.filter(teacher=self).aggregate(models.Sum('nb_period'))['nb_period__sum']
    total_logbook.short_description = 'Solde du carnet du lait'


class LogBookReason(models.Model):
    name = models.CharField('Motif', max_length=50, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Motif de carnet du lait'
        verbose_name_plural = 'Motifs de carnet du lait'


class LogBook(models.Model):
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, verbose_name='Enseignant')
    reason = models.ForeignKey(LogBookReason, on_delete=models.PROTECT, verbose_name='Catégorie de motif')
    input_date = models.DateField('Date de saisie', auto_now_add=True)
    start_date = models.DateField('Date de début')
    end_date = models.DateField('Date de fin')
    nb_period = models.IntegerField('Périodes')
    comment = models.CharField('Commentaire motif', max_length=200, blank=True)

    def __str__(self):
        return '{} : {} pér. - {}'.format(self.teacher, self.nb_period, self.comment)

    class Meta:
        verbose_name = 'Carnet du lait'
        verbose_name_plural = 'Carnets du lait'


class Option(models.Model):
    name = models.CharField("Nom", max_length=100, unique=True)

    def __str__(self):
        return self.name


class ExamEDESession(models.Model):
    year = models.PositiveIntegerField()
    season = models.CharField('saison', max_length=10)

    class Meta:
        verbose_name = "Session d’examen"
        ordering = ['-year', 'season']

    def __str__(self):
        return '{0} {1}'.format(self.year, self.season)


GENDER_CHOICES = (
    ('M', 'Masculin'),
    ('F', 'Féminin'),
)

class Student(models.Model):
    ACQ_MARK_CHOICES = (
        ('non', 'Non acquis'),
        ('part', 'Partiellement acquis'),
        ('acq', 'Acquis'),
    )

    ext_id = models.IntegerField(null=True, unique=True, verbose_name='ID externe')
    first_name = models.CharField(max_length=40, verbose_name='Prénom')
    last_name = models.CharField(max_length=40, verbose_name='Nom')
    gender = models.CharField('Genre', max_length=3, blank=True, choices=GENDER_CHOICES)
    birth_date = models.DateField('Date de naissance', null=True, blank=True)

templates/attribution.html
{% extends "admin/base_site.html" %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}
<style>
  div#period_choice { margin: 0 auto; text-align: center; width: 60%; padding: 0.5em; margin-bottom: 1em; background-color: #EDF3FE;}
  select#section_select { width: 8em; margin-right: 2em; }
  select#period_select { width: 16em; }

  div#student_choice { float: left; width: 18%; }
  select#student_select, select#student_filter { width: 100%; height: auto; }

  div#corp_choice { float: right; width: 18%; }
  select#corp_select, select#corp_filter { width: 100%; height: auto; }
  select#corp_select option.priority { font-weight: bold; }

  div#student_detail { float:left; width: 40%; margin: 1em; padding: 0.5em; border: 3px solid red; min-height: 4em; border-radius: 8px; }
  div#previous_stages { background-color: #EEE; border-radius: 4px; }
  ul#previous_stages_list { display: none; padding-left: 1.5em;}
  span.under_17 { color: red; }

  div#corp_detail { float:right; width: 40%; margin: 1em; padding: 0.5em; border: 3px solid red; min-height: 4em; border-radius: 8px; }
  div#corp_total, div#student_total { font-style: italic; color: gray; }
  div.filled { border-color: green !important; }

  div#training_form { text-align: center; }
  div#buttons_div { margin-top: 1em; }
  input#valid_training { display: none; }

  div#trainings { clear: both; padding-top: 1em; }
  input#export { display: none; margin-left: 2em; }

  .missing { font-style: italic; color: red; }
</style>
{% endblock %}

{% block extrahead %}
  <script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'admin/js/jquery.init.js' %}"></script>
  <script type="text/javascript" src="{% static 'admin/js/admin/RelatedObjectLookups.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/attribution.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/jquery.cookie.js' %}"></script>
{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; Attributions
</div>
{% endblock %}

{% block content %}
<div id="period_choice">
  <form>
    <label for="section_select">Filière:</label>
    <select id="section_select">{% for sect in sections %}<option value="{{ sect.id }}">{{ sect.name }}</option>{% endfor %}</select>
    <label for="period_select">Période:</label>
    <select id="period_select"></select>
  </form>
</div>

<div id="student_choice">
  <form>
    <select id="student_filter" size="1"></select>
    <select id="student_select" size="15"></select>
    <div id="student_total"></div>
  </form>
</div>

<div id="corp_choice">
  <form>
    <select id="corp_filter" size="1"></select>
    <select id="corp_select" size="15"></select>
    <div id="corp_total"></div>
  </form>
</div>

<div id="training_main">

  <div style="overflow: auto;">
    <div id="student_detail"></div>
    <div id="corp_detail"></div>
  </div>
  <div id="training_form">
    <form>{% csrf_token %}
    <div id="referent_choice"><label for="referent_select">Référent école:</label>
      <select id="referent_select"><option value="">-------</option>
        {% for ref in referents %}<option value="{{ ref.id }}">{{ ref }} ({{ ref.num_refs }})</option>{% endfor %}</select>
    </div>
    <div id="contact_choice"><label for="contact_select">Contact institution:</label>
      <select id="contact_select"><option value="">-------</option></select>
    </div>
    <div id="buttons_div"><input id="valid_training" type="button" value="Valider cette pratique professionnelle"></div>
    </form>
  </div>
</div>

<div id="trainings">
  <h3>Pratiques professionnelles planifiées pour la période choisie</h3>
  <ul id="training_list">-
  </ul>
  <form id="list_export" method="get" action="{% url 'stages_export' %}">{% csrf_token %}
    <input id="period" name="period" type="hidden" value="">
    <input id="non_attr" name="non_attr" type="hidden" value="0">
    <input id="export" type="button" value="Exporter la liste">
    <input id="export_non_attr" type="button" value="Exporter la liste des places de PP non attribuées">
  </form>
</div>
{% endblock %}

templates/base.html
{% extends "admin/base_site.html" %}

templates/class.html
{% extends "admin/base_site.html" %}
{% load i18n static %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; <a href="{% url 'classes' %}">Liste des classes</a>
</div>
{% endblock %}

{% block content %}
<h2>Classe {{ klass.name }}
{% if perms.stages.change_klass %}<a class="changelink" href="{% url 'admin:stages_klass_change' klass.pk %}">&nbsp;</a>{% endif %}
</h2>

<div style="float:right;">
    <a href="{% url 'class' object.pk %}?format=xls"><img src="{% static 'img/xls.png' %}" title="Exportation Excel" width="24"></a>
</div>

<div style="margin-bottom: 0.7em;">
Maître de classe : {{ klass.teacher }}<br>
Enseignant-e ECG : {{ klass.teacher_ecg|default_if_none:'-' }}<br>
Enseignant-e EPS : {{ klass.teacher_eps|default_if_none:'-' }}
</div>

<table>
  <thead>
      <th>Nom, prénom</th>
      <th>Date naiss.</th>
      {% if show_option_ase %}<th>Orientation</th>{% endif %}
      {% if show_pp %}<th>Récapitulatif des PP</th>{% endif %}
      {% if show_employeur %}<th>Employeur</th>{% endif %}
  </thead>
{% for student in students %}
  <tr class="{% cycle 'row1' 'row2' %}">
      <td><a href="{% url 'student-comment' student.pk %}">{{ student }}</a></td>
      <td>{{ student.birth_date }}</td>
      {% if show_option_ase %}
      <td>{{ student.option_ase|default_if_none:'-' }}</td>
      {% endif %}
      {% if show_pp %}
      {% for train in student.training_set.all %}
      <td>{{ train.availability.period }}<br>{{ train.availability.corporation }}<br>
        {% if train.comment %}<div style="float: right;"><img src="{% static 'admin/img/icon-unknown.svg' %}" title="{{ train.comment }}"></div>{% endif %}
        <i>{{ train.availability.domain }}</i></td>
      {% endfor %}
      {% endif %}
      {% if show_employeur %}<td>{{ student.corporation.name }}, {{ student.corporation.city }}</td>{% endif %}
  </tr>
{% endfor %}
</table>
{% endblock %}

templates/class_list_for_reports.html
{% extends "admin/base_site.html" %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">Accueil</a>
&rsaquo; Envoi des bulletins scolaires
</div>
{% endblock %}

{% block content %}
    <h2>Liste de classe {{ object.name }}</h2>

    <table>
    {% for student in students %}
    <tr class="{% cycle 'row1' 'row2' %}">
        <td>{{ student.full_name }} </td>
        <td>{{ student.corporation }}</td>
        <td><a class="button" href="{% url 'send-student-reports' student.id semestre %}">Envoyer bull. sem.1</a></td>
    </tr>
    {% endfor %}
    </table>
{% endblock %}

templates/classes.html
{% extends "admin/base_site.html" %}

{% block extrastyle %}{{ block.super }}
<style>
  div.section {border: 1px solid #ccc; float: left; margin-right: 5em;}
</style>
{% endblock %}

{% block content %}
<h2>Liste des classes</h2>

{% regroup object_list by section as classes %}

{% for section in classes %}
  <div class="section">
  <table>
  <tr><td><b>{{ section.grouper }}</b></td></tr>
  {% for class in section.list %}
    <tr class="{% cycle 'row1' 'row2' %}">
      <td><a href="{% url 'class' class.pk %}">{{ class.name }}</a></td>
      <td>{{ class.num_students }} étudiants</td>
    </tr>
  {% endfor %}
  </table>
  </div>
{% endfor %}
{% endblock %}

templates/classes_reports.html
{% extends "admin/base_site.html" %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">Accueil</a>
&rsaquo; Préparation des bulletins
</div>
{% endblock %}

{% block content %}
    <h2>Liste des classes FE</h2>

    <table>
    {% for klass in object_list %}
    <tr class="{% cycle 'row1' 'row2' %}">
        <td>{{ klass.name }} </td>
            <td><a class="button" href="{% url 'import-reports' klass.id semestre %}">Importer bulletins CLOEE</a></td>
            {% if semestre == 1 %}
                {% if klass.test_bulletins_sem1 %}
                    <td><a class="button" href="{% url 'send-klass-reports' klass.id 1 %}">Envoyer bulletins</a></td>
                {% endif %}
            {% else %}
                {% if klass.test_bulletins_sem2 %}
                    <td><a class="button" href="{% url 'send-klass-reports' klass.id 2 %}">Envoyer bulletins</a></td>
                {% endif %}
            {% endif %}
    </tr>
    {% endfor %}
    </table>
{% endblock %}

templates/corporation_merge.html
{% extends "admin/base_site.html" %}

{% block extrahead %}{{ block.super }}
<script type="text/javascript" src="{% url 'admin:jsi18n' %}"></script>
{{ form.media }}
{% endblock %}

{% block content %}
<h2>Fusionner deux institutions</h2>

<form method="post">{% csrf_token %}
    <div>{{ form.corp_merge_from.label_tag }} {{ form.corp_merge_from }}
        <ul>{% for contact in contacts_from %}
            <li>{{ contact }}</li>
        {% endfor %}
        </ul>
    </div>
    <div>{{ form.corp_merge_to.label_tag }} {{ form.corp_merge_to }}
        <ul>{% for contact in contacts_to %}
            <li>{{ contact }}</li>
        {% endfor %}
        </ul>
    </div>
    <input name="step" type="hidden" value="{{ step }}">
    <button>Fusionner</button>
</form>
{% endblock %}

templates/email_base.html
{% extends "admin/base_site.html" %}
{% load i18n static %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; {{ title }}
</div>
{% endblock %}

{% block content %}
<h2>{{ person }}</h2>
<form name="confirmation" action="" method="post">{% csrf_token %}
<table>
{{ form.as_table }}
<tr><td><input type="submit" value="Envoyer"></td></tr>

</table>
{% block post_form %}{% endblock %}
</form>
{% endblock %}

templates/student_comment.html
{% extends "admin/base_site.html" %}
{% load static %}

{% block extrastyle %}{{ block.super }}
<style>
span.label, form label { font-weight: bold; }
div.block { width: 45%; display: inline-block; vertical-align: top; }
textarea { width: 90%; }
button.button { padding: 10px 15px; }
fieldset { border: 1px solid #ccc; padding: 8px; }
fieldset p { margin: 0; }
input[name$='titre'] { width: 40em; }
</style>
{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">Accueil</a>
&rsaquo; <a href="{% url 'classes' %}">Liste des classes</a>
&rsaquo; <a href="{% url 'class' student.klass.pk %}">{{ student.klass.name }}</a>
</div>
{% endblock %}

{% block content %}
<h2>{{ student }}
{% if perms.stages.change_student %}<a class="changelink" href="{% url 'admin:stages_student_change' student.pk %}">&nbsp;</a>{% endif %}
</h2>

<div class="block">
    <table>
        <tr><td><span class="label">Date de naissance :</span></td><td>{{ student.birth_date }}</td></tr>
        <tr><td><span class="label">Adresse :</span></td><td>{{ student.street }}, {{ student.pcode }} {{ student.city }} {{ student.district }}</td></tr>
    </table>
</div>
<div class="block">
    <table>
        <tr><td><span class="label">Courriel :</span></td><td>{{ student.email }}</td></tr>
        <tr><td><span class="label">Tél :</span></td><td>{{ student.tel }}</td></tr>
        <tr><td><span class="label">Portable :</span></td><td>{{ student.mobile }}</td></tr>
    </table>
</div>
{% if student.option_ase %}
<div class="block"><span class="label">Orientation :</span> {{ student.option_ase }}</div>
{% endif %}

{% if form %}
<form method="post" action="." enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_p }}

    {{ form.files_fset.management_form }}
    {% for frm in form.files_fset %}
        <fieldset>{{ frm.as_p }}</fieldset>
    {% endfor %}
    <button class="button" type="submit">Enregistrer</button>
</form>
{% endif %}

{% endblock %}